version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - db
    env_file:
      - '.env'

  db:
    image: "postgres:16"

    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    ports:
      - "5435:5432"

    volumes:
      - ./data:/var/lib/postgresql/data
