"""empty message

Revision ID: 9d7ed5687ef4
Revises: a3f94c8f75f8
Create Date: 2023-11-09 10:58:16.801141

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d7ed5687ef4"
down_revision: Union[str, None] = "a3f94c8f75f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=80),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.String(length=80),
        type_=sa.VARCHAR(length=30),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
