"""empty message

Revision ID: ea5b93b1ec3f
Revises: 3b5838e76dc6
Create Date: 2023-11-20 10:39:34.354683

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea5b93b1ec3f"
down_revision: Union[str, None] = "3b5838e76dc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("image_s3_path", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "is_blocked", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_blocked")
    op.drop_column("user", "image_s3_path")
    # ### end Alembic commands ###
