name: User Managment CI CD

on:
  push:
    branches: ["dev", "feature"]
  # pull_request:
    # branches: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: TestUserManagement
          
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with Black
        run: |
          black src
          black --check src

      - name: Test with pytest
        working-directory: ./src
        run: python -m pytest tests/units

      - name: Integration tests
        working-directory: ./src
        run: python -m pytest tests/integration
        env: 
          DB_USER: test
          DB_PASSWORD: test
          DB_HOST: postgres
          DB_PORT: 5432
          DB_NAME: TestUserManagement
    
      
